### ISSUE TITLE
(Question) How do I take advantage of the collaborative editing ready features?

### ISSUE THREAD

**Issue by Alcachofraz** [fleather-editor/fleather#102]
I'm trying to develop an OT collaborative text editor, and I think Fleather could help me. In the Pub.dev page it says:

"Using [Quill.js Delta](https://quilljs.com/docs/delta) as underlying data format by [Parchment](https://github.com/fleather-editor/fleather/blob/master/packages/parchment/README.md), Fleather is ready for collaborative editing using [OT](https://en.wikipedia.org/wiki/Operational_transformation) (Not provided as a built-in functionality)"

As I'm not familiar with such technologies, I'm a bit lost in what Fleather actually provides in that sense.

From my point of view, I'd need a callback for when an operation is performed (insert, remove, ...). The default TextField of Flutter is no use for my use-case since onChanged only gives me the full text, and not the inserted/removed text (or character) and the corresponding index.

I hope I managed to explain my problem. Is there anyone who could point me in the right direction?

**Comment by cgestes** [comment]
start here: https://github.com/jotshq/fleather_demo_collab :)

**Comment by amantoux** [comment]
Closing (feel free to re-open if deemed necessary)
