### ISSUE TITLE
How to change the editor font size

### ISSUE THREAD

**Issue by MohammedSalehelShazly** [fleather-editor/fleather#107]
I don't mean `Heading` attributes, I want to give the font a special font size.
I tried to wrap `FleatherEditor` with `Theme` and changed `Textheme` but It was not successful.

**Comment by amantoux** [comment]
I'll take a look

**Comment by Amir-P** [comment]
In order to change the look of `FleatherEditor` and `FleatherField` you need to use `FleatherTheme` and not `Theme`. I gave it a try and it's working. @amantoux @MohammedSalehelShazly 

```dart
@override
Widget build(BuildContext context) {
  final defaultTheme = FleatherThemeData.fallback(context);
  return FleatherTheme(
    data: defaultTheme.copyWith(
      paragraph: TextBlockTheme(
        style: defaultTheme.paragraph.style.copyWith(fontSize: 40),
        spacing: defaultTheme.paragraph.spacing,
      ),
    ),
    child: FleatherEditor(...),
  );
}
```

**Comment by Amir-P** [comment]
BTW, we need to add a `copyWith` to theme related objects for easier usage (e.g. `TextBlockTheme` don't have a `copyWith` method). @amantoux
