### ISSUE TITLE
Can not see the example

### ISSUE THREAD

**Issue by luohao123** [fleather-editor/fleather#112]
Can not see the example

**Comment by amantoux** [comment]
Can you be more specific and describe more the problem you are facing?

**Comment by luohao123** [comment]
https://github.com/fleather-editor/fleather/blob/master/example/lib/main.dart

Please open it

**Comment by amantoux** [comment]
https://github.com/fleather-editor/fleather/blob/master/packages/fleather/example/lib/main.dart

try this

**Comment by amantoux** [comment]
You need to use the latest Flutter version on `stable` channel

**Comment by NeoChow** [comment]
I could build the example successfully now after change flutter channel to stable. Thanks.
