### ISSUE TITLE
assign method to text

### ISSUE THREAD

**Issue by hamidjalili59** [fleather-editor/fleather#123]
This isn't problem, I want a new feature,
----------------------------------------------
Can I apply a method to a text, like onLaunchUrl in FleatherEditor Widget , which is executed when we consider a link for a text, but I want to consider another task for the text and have it executed when I click on that part of the text?

**Comment by amantoux** [comment]
You can use custom embeds to build you own inline widget
You'll find an example here

https://github.com/Amir-P/fleather_mention

**Comment by Amir-P** [comment]
I think it's something we need to provide. Some kind of callback which gets executed before we handle the gestures. WDYT? @amantoux

**Comment by amantoux** [comment]
> I think it's something we need to provide. Some kind of callback which gets executed before we handle the gestures. WDYT? @amantoux

Yes, it could be simpler for user
