### ISSUE TITLE
How can i implement a custom syntax, such as h4

### ISSUE THREAD

**Issue by lbhfuture** [fleather-editor/fleather#138]
This is just a question, but i cannot find a correct tag.

As fleather has only 3 level headings h1 ~ h3, if i want to use more heading level, what should i do ? The online demo https://fleather-editor.github.io/demo/index.html#/ has h4 ~ h6, but i cannot find how to do it, could you show me a tip or demo code? Thx

**Comment by lbhfuture** [comment]
Got it, thx.

**Comment by Amir-P** [comment]
The new version with additional heading attributes (v1.9.0) is available now: https://pub.dev/packages/fleather @lbhfuture
