### ISSUE TITLE
Light theme inline code wrong color

### ISSUE THREAD

**Issue by lukepighetti** [fleather-editor/fleather#147]
## Steps to Reproduce

1. Create MaterialApp using Material3

```dart
MaterialApp(
  theme: ThemeData(useMaterial3: true)
  ...
);
```

2. Observe the foreground color for an inline code span

![Simulator Screenshot - iPhone 14 (16 2) - 2023-06-30 at 10 07 08](https://github.com/fleather-editor/fleather/assets/666539/91fd0846-496d-46f1-a888-e3ceeb2a0d5c)

## Environment
- iOS Simulator
- Flutter version `3.10.5` stable
- Fleather version `fleather: ^1.9.`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by amantoux** [comment]
Indeed we have not tested with Material 3. We address that soon
