### ISSUE TITLE
How to define shortcut for a custom widget

### ISSUE THREAD

**Issue by lbhfuture** [fleather-editor/fleather#149]
**Is your feature request related to a problem? Please describe.**
Is there anyway to define shortcut for a custom widget?

**Describe the solution you'd like**
Is there anyway to define shortcut for a custom widget? For example, when I typed ```json and followed by Enter , it should auto display my custom view with prettied json format. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Amir-P** [comment]
We don't have any syntax highlighting or formatting for code blocks yet. But if you type ``` in the editor you will get a code block and this behavior is accomplished using `MarkdownBlockShortcutsInsertRule` from Parchment package. You can introduce your own shortcuts by adding a new heuristic rule. Take a look at the [example](packages/fleather/example/lib/main.dart) for how to add a new rule:

https://github.com/fleather-editor/fleather/blob/a49cd20c8786184dee22514732f91fd10cb4ccdc/packages/fleather/example/lib/main.dart#L46-L57

https://github.com/fleather-editor/fleather/blob/a49cd20c8786184dee22514732f91fd10cb4ccdc/packages/fleather/example/lib/main.dart#L145-L183
