### ISSUE TITLE
Typing Japanese alphabet does not yield correct result

### ISSUE THREAD

**Issue by alex-yolabs** [fleather-editor/fleather#150]
## Steps to Reproduce
1. Open system setting
2. Select "Keyboard Tab"
3. Select "Edit" under Text input - Input Sources
4. Click on the "+" sign at the lower bottom
5. Select "Japanese - Romaji" and "add"
6. Make sure "Show input menu in menu bar" is enabled
7. Click "Done"
8. On the top right screen, you should see [A] icon. Click on it and change it to [あ]
9. Click again and uncheck ”Live conversion" because it does some smart conversion but the behavior is inconsistent.
10. In [あ] Japanese input mode, type "kyouha", hit [space] to convert it to Kanji, and finally hit [enter] key to confirm the conversion.

### Expected result:
`今日は`

### Actual result:
`きょうは今日は`

## Environment
- Chrome
- Flutter version: 3.10.5
- Fleather version: 1.9.0
- Parchment version: 1.9.0

## Logs
There is no error log when the issue happens.

## Screen recording
https://github.com/fleather-editor/fleather/assets/81038569/587d789f-81dc-4607-bf1b-1290d3576a8e

**Comment by amantoux** [comment]
@alex-yolabs Do you confirm you do not reproduce this behaviour with Flutter's `TextField`? And if not, you confirm that it doesn't require any configuration to support Kanji conversion?

**Comment by alex-yolabs** [comment]
@amantoux Hi, Thank you for your quick response.

Yes, I confirm that this issue is not reproducible with Flutter's TextField, and yes, no extra configuration is needed to support Kanji conversion.

https://github.com/fleather-editor/fleather/assets/81038569/bbc112f9-e8ca-4d84-be3d-815537b6d85a

**Comment by alex-yolabs** [comment]
@amantoux Is there any update on this issue? Thank you!

**Comment by amantoux** [comment]
@alex-yolabs sorry, I won't have time to look at it before next week probably.(@Amir-P )
feel free to suggest a fix

**Comment by Amir-P** [comment]
Hey @alex-yolabs, Thanks for creating the issue. I may find some time today to take a look at it.
CC:  @amantoux

**Comment by Amir-P** [comment]
It should be fixed now on the master channel. Could you check? @alex-yolabs

**Comment by Amir-P** [comment]
It should be fixed now on the master channel (Flutter). But Fleather won't work with Flutter's master channel. We have to wait for the next stable release. @alex-yolabs @amantoux

**Comment by alex-yolabs** [comment]
@Amir-P 
Thank you so much for working on this! Really appreciate it. I look forward to the next Fleather version!

**Comment by Amir-P** [comment]
> Thank you so much for working on this! Really appreciate it. I look forward to the next Fleather version!

I hope you find it helpful. You can support the project by giving it a star! ⭐️ @alex-yolabs 

I'm gonna keep this issue open until it lands on master.

**Comment by Amir-P** [comment]
I think this is fixed now with Flutter 3.16. Can you check please? @alex-yolabs

**Comment by alex-yolabs** [comment]
@Amir-P Thank you! I will give it a shot and report. Appreciate it!
