### ISSUE TITLE
Direction and alignment resets after pressing enter

### ISSUE THREAD

**Issue by Amir-P** [fleather-editor/fleather#158]
## Steps to Reproduce

1. Change direction or alignment
2. Press enter

## Environment
- Happens on all platforms
- Flutter version 3.13.2
- Fleather version 1.10.0

https://github.com/fleather-editor/fleather/assets/8766492/637c50ba-160a-479f-a419-f7f286220601

**Comment by Amir-P** [comment]
First bad commit: ad8a0728e6692948920cc587a5ed622c8dbe9ebd

**Comment by VergoEcho** [comment]
Also faced this issue in my project🥲, waiting and hoping for updates🙏🏻

**Comment by Amir-P** [comment]
@VergoEcho we're working on a solution to this problem and possible other conflicts between heuristics. In the meantime, If you happen to don't need auto link format, you can use this as heuristics (Not including `AutoFormatLinksRule`):

```
ParchmentHeuristics(
    formatRules: [
      FormatLinkAtCaretPositionRule(),
      ResolveLineFormatRule(),
      ResolveInlineFormatRule(),
      // No need in catch-all rule here since the above rules cover all
      // attributes.
    ],
    insertRules: [
      // Embeds
      InsertBlockEmbedsRule(),
      ForceNewlineForInsertsAroundBlockEmbedRule(),
      // Blocks
      AutoExitBlockRule(), // must go first
      PreserveBlockStyleOnInsertRule(),
      MarkdownBlockShortcutsInsertRule(),
      // Lines
      PreserveLineStyleOnSplitRule(),
      ResetLineFormatOnNewLineRule(),
      AutoTextDirectionRule(),
      // Inlines
      PreserveInlineStylesRule(),
      // Catch-all
      CatchAllInsertRule(),
    ],
    deleteRules: [
      EnsureEmbedLineRule(),
      PreserveLineStyleOnMergeRule(),
      CatchAllDeleteRule(),
    ],
  )
```

**Comment by VergoEcho** [comment]
Thank you, for a fast answer⚡

**Comment by VergoEcho** [comment]
> @VergoEcho we're working on a solution to this problem and possible other conflicts between heuristics. In the meantime, If you happen to don't need auto link format, you can use this as heuristics (Not including `AutoFormatLinksRule`):
> 
> ```
> ParchmentHeuristics(
>     formatRules: [
>       FormatLinkAtCaretPositionRule(),
>       ResolveLineFormatRule(),
>       ResolveInlineFormatRule(),
>       // No need in catch-all rule here since the above rules cover all
>       // attributes.
>     ],
>     insertRules: [
>       // Embeds
>       InsertBlockEmbedsRule(),
>       ForceNewlineForInsertsAroundBlockEmbedRule(),
>       // Blocks
>       AutoExitBlockRule(), // must go first
>       PreserveBlockStyleOnInsertRule(),
>       MarkdownBlockShortcutsInsertRule(),
>       // Lines
>       PreserveLineStyleOnSplitRule(),
>       ResetLineFormatOnNewLineRule(),
>       AutoTextDirectionRule(),
>       // Inlines
>       PreserveInlineStylesRule(),
>       // Catch-all
>       CatchAllInsertRule(),
>     ],
>     deleteRules: [
>       EnsureEmbedLineRule(),
>       PreserveLineStyleOnMergeRule(),
>       CatchAllDeleteRule(),
>     ],
>   )
> ```

I tried these heuristics, and the problem still persists. 
I'm using fleather: ^1.10.0

**Comment by Amir-P** [comment]
Sorry for the late response. I was really busy. @amantoux is working on this issue and hopefully we're going to close it with #181 . @VergoEcho
