### ISSUE TITLE
Improving heuristics

### ISSUE THREAD

**Issue by Amir-P** [fleather-editor/fleather#162]
Working on a fix for #158, I noticed the limitations of current heuristics and their problems:

1. Heuristics are applied sequential and after the first heuristic successfully applied (returned a delta) we ignore the ones after that. This causes problem when two heuristics overlap. For example `PreserveLineStyleOnSplitRule` tries to set the line style to the newly created line after we split a line in two. For example `AutoFormatLinksRule` tries to auto format links when a new line or space added after a valid link. Only one of these can work and it's a matter of order.
2. Insertion heuristics are applied on each change and these changes can vary from changes affecting a single character insertions to multi line texts. Current heuristics won't work in cases where user inputs multiple characters at a time. For example `AutoFormatLinksRule` won't work if user paste two empty lines ("\n\n") at the end of a valid line.

I think we need to rethink the whole model of applying heuristics and rewrite it. Do you have any thoughts on how we can improve it? @cgestes @zaynetro @amantoux

**Comment by amantoux** [comment]
I guess we can close this now, #181 should address this
