### ISSUE TITLE
Code mode number display incorrect

### ISSUE THREAD

**Issue by fcunnn** [fleather-editor/fleather#167]
Error as shown in the picture

  ![Image](https://github.com/fcunnn/yann/blob/main/1.png)

**Comment by amantoux** [comment]
@fcunnn I cannot reproduce on web or windows
On which platform did you observe this behavior?
Any customization worth mentioning (theme for example)?

**Comment by fcunnn** [comment]
The versions of my OS and VS are as follows

```
Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-x64, locale zh-Hans-CN)
VS Code (version 1.83.0)
```

However, I just tried again and it is true that the problem cannot be reproduced. It seems that this question is a random one and has taken up your valuable time. I am sorry for taking up your valuable time. Thank you very much for your reply.
