### ISSUE TITLE
Alignment button to rule them all!

### ISSUE THREAD

**Issue by VergoEcho** [fleather-editor/fleather#175]
I want to save space in fleather toolbar and think, that it would be nice to have one button ("...to rule them all!!!") that changes alignment values in a circle, as an alternative option to separate buttons that are responsible only one alignment.

I have implemented this functionality by code placed below, but also want to show what alignment is used dynamically when the cursor changes position like in other default buttons. And again, I think this alignment button option would be nice to have out of the box

```
 toggleAlignment() {
    final alignment = fleatherController.getSelectionStyle().lineAttributes;
    print(alignment);

    if (alignment.contains(ParchmentAttribute.center)) {
      fleatherController.formatSelection(ParchmentAttribute.right);
      return;
    }
    if (alignment.contains(ParchmentAttribute.right)) {
      fleatherController.formatSelection(ParchmentAttribute.left);
      return;
    }
    fleatherController.formatSelection(ParchmentAttribute.center);
    return;
  }
```

**Comment by Amir-P** [comment]
Thanks for your suggestion. I've implement this exact behavior in a company application but wanted to keep everything consistent while implementing it in Zefyr (https://github.com/memspace/zefyr/pull/565). It is really hard to come up with something that fits all use cases and instead, we provide a really simple toolbar which just works and the option to implement your own toolbar. @VergoEcho
