### ISSUE TITLE
TextDirection resets after newline is inserted.

### ISSUE THREAD

**Issue by SaeedZeroOne** [fleather-editor/fleather#200]
## Steps to Reproduce

Hey there. 
When I insert an RTL line like 'سلام', as you see below in the logs, everything works and the direction is set to .rtl, however when I press Enter, all of a sudden the node that contains the RTL line resets and all the directionality data is lost (the log shows that too).

Thanks.

## Environment
- OS Android
- Flutter version 3.16
- Fleather's latest version

## Logs

```I/flutter (24841): ¶ ⟨س⟩ ⏎ {direction: rtl, alignment: right}  ::  direction: rtl
I/flutter (24841): ¶ ⟨سل⟩ ⏎ {direction: rtl, alignment: right}  ::  direction: rtl
I/flutter (24841): ¶ ⟨سلا⟩ ⏎ {direction: rtl, alignment: right}  ::  direction: rtl
I/flutter (24841): ¶ ⟨سلام⟩ ⏎ {direction: rtl, alignment: right}  ::  direction: rtl
I/flutter (24841): ¶ ⟨سلام⟩ ⏎  ::  null
I/flutter (24841): ¶  ⏎ {direction: rtl, alignment: right}  ::  direction: rtl
I/flutter (24841): ¶ ⟨سلام⟩ ⏎  ::  null
I/flutter (24841): ¶  ⏎ {direction: rtl, alignment: right}  ::  direction: rtl
I/flutter (24841): ¶ ⟨سلام⟩ ⏎  ::  null
I/flutter (24841): ¶  ⏎ {direction: rtl, alignment: right}  ::  direction: rtl```

**Comment by Amir-P** [comment]
Hi @SaeedZeroOne. Using the example app and following steps in the issue, I'm unable to reproduce the issue and It works as expected. Can you attach the code you're running and your `pubspec.yaml` too?

https://github.com/fleather-editor/fleather/assets/8766492/c822e89a-5c7a-4731-8d93-71749d95eb26

**Comment by SaeedZeroOne** [comment]
> Hi @SaeedZeroOne. Using the example app and following steps in the issue, I'm unable to reproduce the issue and It works as expected. Can you attach the code you're running and your `pubspec.yaml` too?
> 
>  recording.mov

It turns out that I haven't been using the new `PreserveLineFormatOnNewLineRule()` class. Thank you.
