### ISSUE TITLE
How to make editor scroll down as user types below the keyboard?

### ISSUE THREAD

**Issue by ember11498** [fleather-editor/fleather#201]
So right now what I have is very simple but when the user starts typing in the editor its fine at first but then as user keeps typing when it reaches the bottom it starts going below/behind the keyboard. How can I make it scroll down as user keeps typing and adding new lines?

`    import 'package:client/utils/extensions/buildcontext.dart';
    import 'package:fleather/fleather.dart';
    import 'package:flutter/material.dart';
    import 'package:go_router/go_router.dart';

    class FleatherTextEditor extends StatefulWidget {
      const FleatherTextEditor({super.key});

      @override
      State<FleatherTextEditor> createState() => _FleatherTextEditorState();
    }

    class _FleatherTextEditorState extends State<FleatherTextEditor> {
      late final ParchmentDocument doc;
      late final FleatherController controller;

      @override
      void initState() {
        super.initState();
        doc = ParchmentDocument();
        doc.insert(0, 'Start writting...');
        controller = FleatherController(document: doc);
      }

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          resizeToAvoidBottomInset: true,
          body: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 600),
            child: SafeArea(
              child: Column(
                children: [
                  ElevatedButton(
                    style: ButtonStyle(
                        backgroundColor:
                            MaterialStatePropertyAll(context.colorScheme.primary)),
                    onPressed: () => context.pop(),
                    child: Text(
                      'Save',
                      style: context.regular,
                    ),
                  ),
                  const Divider(),
                  FleatherEditor(
                    controller: controller,
                    scrollable: true,
                    autofocus: true,
                    padding: const EdgeInsets.symmetric(
                      horizontal: 8,
                    ),
                  ),
                  FleatherToolbar.basic(
                    controller: controller,
                    padding: const EdgeInsets.all(0),
                  ),
                ],
              ),
            ),
          ),
        );
      }
    }

`

**Comment by ember11498** [comment]
I manage to make it work like this for some reason this works. It still need some changes but the goal of scrolling as user types works now

`    import 'package:client/utils/extensions/buildcontext.dart';
    import 'package:fleather/fleather.dart';
    import 'package:flutter/material.dart';
    import 'package:go_router/go_router.dart';

    class FleatherTextEditor extends StatefulWidget {
      const FleatherTextEditor({super.key});

      @override
      State<FleatherTextEditor> createState() => _FleatherTextEditorState();
    }

    class _FleatherTextEditorState extends State<FleatherTextEditor> {
      late final ParchmentDocument doc;
      late final FleatherController controller;

      @override
      void initState() {
        super.initState();
        doc = ParchmentDocument();
        doc.insert(0, 'Start writting...');
        controller = FleatherController(document: doc);
      }

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          resizeToAvoidBottomInset: true,
          body: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 600),
            child: SafeArea(
              child: Stack(
                children: [
                  Column(
                    children: [
                      ElevatedButton(
                        onPressed: () => context.pop(),
                        style: ButtonStyle(
                          backgroundColor:
                              MaterialStatePropertyAll(context.colorScheme.primary),
                        ),
                        child: Text('Save', style: context.regular),
                      ),
                      Expanded(
                        child: FleatherEditor(
                          controller: controller,
                          autofocus: true,
                          padding: const EdgeInsets.symmetric(
                            horizontal: 8,
                          ),
                        ),
                      ),
                    ],
                  ),
                  FleatherToolbar.basic(controller: controller),
                ],
              ),
            ),
          ),
        );
      }
    }
`

**Comment by amantoux** [comment]
Closing this as you seem to have found a solution. Feel free to re-open.
