### ISSUE TITLE
I would like to when I tap on color buttons or SelectHeadingButton for the keyboard to say active. I find it a bit annoying the keyboard dismissing everytime user taps to change colors or headings

### ISSUE THREAD

**Issue by ember11498** [fleather-editor/fleather#202]
Right now keyboard dismises when we tap on color or heading buttons. After user select the color or the heading the keyboard shows up again but wouldnt it be better if the keyboard stayed always active? I would like to have that option

**Comment by amantoux** [comment]
We need to stop using modals to show the color picker / headings selector and use OverlayEntry instead
