### ISSUE TITLE
Notion-like Menu toolbar for text actions like Bold, Italic etc

### ISSUE THREAD

**Issue by nialljawad96** [fleather-editor/fleather#205]
**Is your feature request related to a problem? Please describe.**
Thanks for making this package. It's really simple and much better than the others. Is there a way to create an appearing/disappearing menu toolbar for FleatherToolbar.basic? A bit how Notion only show the toolbar when you have text selected. I'd really love this.

**Describe the solution you'd like**
An appearing/disappearing menu toolbar for FleatherToolbar.basic that only appears when text is selected. If possible, some ways to customise it's appearance too. 

**Describe alternatives you've considered**
Appears to be a toolbar parameter in FleatherField? But not clear as to what its purpose is. I've tried to use but nothing is appearing.

**Comment by amantoux** [comment]
We have the building blocks to achieve this!
Feel free to propose another another toolbar builder

**Comment by nialljawad96** [comment]
@amantoux So it's available already? Is that what the toolbar parameter is? Could you provide an example of how to use this? I've tried to add a similar container here for example, but I'm getting huge renderflex errors:

`  toolbar: Container(
                        width: 30,
                        height: 30,
                        color: Colors.black,
                      ),`

**Comment by amantoux** [comment]
@nialljawad96 it needs a dev in Fleather. At the moment the contextual menu mimics the native toolbar and relies on this builder
https://github.com/fleather-editor/fleather/blob/5c77e83585e8019f0628d5e0fb941d2ecd243647/packages/fleather/lib/src/widgets/editor.dart#L38C1-L38C1
You can propose another toolbar implementation in PR if you wish

**Comment by nialljawad96** [comment]
@amantoux The contextmenubuilder parameter doesn't do anything. Why is it in there if I can't create a widget from it? Are you saying the parameter is in FleatherField, but doesn't work?

**Comment by nialljawad96** [comment]
Closing as able to solve using #217
