### ISSUE TITLE
FleatherTextField not working when `SemanticsBinding.instance.ensureSemantics()` is enabled.

### ISSUE THREAD

**Issue by niteshsh4rma** [fleather-editor/fleather#206]
## Steps to Reproduce

1. Use example from the fleather-editor repository
2. Write `SemanticsBinding.instance.ensureSemantics()` in `main.dart`
3. Try typing into textfield

## Environment
- Web
- Flutter 3.16.5 (stable)
- Fleather 1.10.0

**Comment by niteshsh4rma** [comment]
@Amir-P if you can look into this in priority, it would be helpful.

**Comment by amantoux** [comment]
@niteshsh4rma where are you placing `SemanticsBinding.instance.ensureSemantics()` exactly?

**Comment by amantoux** [comment]
@niteshsh4rma The issue seems to be in Flutter https://github.com/flutter/flutter/issues/129324#issuecomment-1813048640

**Comment by niteshsh4rma** [comment]
> @niteshsh4rma The issue seems to be in Flutter [flutter/flutter#129324](https://github.com/flutter/flutter/issues/129324)

Yes I saw that, but is there any hotfix to this, if possible?

**Comment by amantoux** [comment]
There might be a workaround.

Surround `FleatherField` with a `Navigator` widget to ensure it renders before `FleatherField` to avoid the problem described here https://github.com/flutter/flutter/pull/138446

```dart
Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(elevation: 0, title: Text('Fleather Demo')),
      body: _controller == null
          ? Center(child: const CircularProgressIndicator())
          : Navigator(
              onGenerateRoute: (_) => MaterialPageRoute(
                builder: (_) => Column(
                  children: [
                    FleatherToolbar.basic(controller: _controller!),
                    Divider(
                        height: 1, thickness: 1, color: Colors.grey.shade200),
                    Expanded(
                      child: FleatherEditor(
                        controller: _controller!,
                        focusNode: _focusNode,
                        padding: EdgeInsets.only(
                          left: 16,
                          right: 16,
                          bottom: MediaQuery.of(context).padding.bottom,
                        ),
                        onLaunchUrl: _launchUrl,
                        maxContentWidth: 800,
                        embedBuilder: _embedBuilder,
                        spellCheckConfiguration: SpellCheckConfiguration(
                            spellCheckService: DefaultSpellCheckService(),
                            misspelledSelectionColor: Colors.red,
                            misspelledTextStyle:
                                DefaultTextStyle.of(context).style),
                      ),
                    ),
                  ],
                ),
              ),
            ),
    );
```

Let me know if this works for you

**Comment by niteshsh4rma** [comment]
> There might be a workaround.
> 
> Surround `FleatherField` with a `Navigator` widget to ensure it renders before `FleatherField` to avoid the problem described here [flutter/flutter#138446](https://github.com/flutter/flutter/pull/138446)
> 
> ```dart
> Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(elevation: 0, title: Text('Fleather Demo')),
>       body: _controller == null
>           ? Center(child: const CircularProgressIndicator())
>           : Navigator(
>               onGenerateRoute: (_) => MaterialPageRoute(
>                 builder: (_) => Column(
>                   children: [
>                     FleatherToolbar.basic(controller: _controller!),
>                     Divider(
>                         height: 1, thickness: 1, color: Colors.grey.shade200),
>                     Expanded(
>                       child: FleatherEditor(
>                         controller: _controller!,
>                         focusNode: _focusNode,
>                         padding: EdgeInsets.only(
>                           left: 16,
>                           right: 16,
>                           bottom: MediaQuery.of(context).padding.bottom,
>                         ),
>                         onLaunchUrl: _launchUrl,
>                         maxContentWidth: 800,
>                         embedBuilder: _embedBuilder,
>                         spellCheckConfiguration: SpellCheckConfiguration(
>                             spellCheckService: DefaultSpellCheckService(),
>                             misspelledSelectionColor: Colors.red,
>                             misspelledTextStyle:
>                                 DefaultTextStyle.of(context).style),
>                       ),
>                     ),
>                   ],
>                 ),
>               ),
>             ),
>     );
> ```
> 
> Let me know if this works for you

Nope, it didn't worked.

**Comment by Amir-P** [comment]
What about using CanvasKit renderer for Web? If that didn't workout too, I think the only way for now is to not use the `SemanticsBinding.instance.ensureSemantics()` on Web. @niteshsh4rma

**Comment by amantoux** [comment]
@niteshsh4rma sorry but at the moment, you should remove this instruction for web.

**Comment by amantoux** [comment]
Closing this for now. Feel free to re-open when the fix is available in Flutter & if the problem persists
