### ISSUE TITLE
How to insert image and video or any custom widget

### ISSUE THREAD

**Issue by Chandu-bs** [fleather-editor/fleather#212]
How can we insert an image either through link or an local image in the editor, that to with the image icon in the tool bar, and also is there any chance that if we copied an image from some where and pasted it in the editor, the image should be pasted same as the text.

If so, any example to lead me through?

**Comment by Chandu-bs** [comment]
If you don't mind, can you point me out where exactly I can know more about these i.e embedding an widget inside the editor, as the editor document is predefined json file, I want to know how it works if User wants to give input directly in the editor and save the data, then how can we embed any custom widget!

**Comment by Amir-P** [comment]
I added image picker functionality to the example app. It's not merged yet so if you want you can check the code in https://github.com/fleather-editor/fleather/pull/218. @Chandu-bs

**Comment by Chandu-bs** [comment]
A small doubt, after inserting a custom widget of our choice, how to make the cursor placed right after the widget embedded, as I was getting few errors
'''
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 478:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 590:30                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1385:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:478:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 478:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 590:30                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1385:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:478:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 478:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 590:30                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1385:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
'''

**Comment by Amir-P** [comment]
> The cursor placed right after the widget embedded was getting few errors like below

Did you encounter this issue running my example? What were the steps? On what platform you were running?

> And one more thing can we use same and use file picker for video too?, Is there any thing that should be defined in BlockEmbed etc?, for image its fine, but for youtube video and formula expression etc, can we directly embed?

There's no difference. Update the `embedBuilder` to build the widget you want and add it to your document too. @Chandu-bs

**Comment by Chandu-bs** [comment]
> Did you encounter this issue running my example? What were the steps? On what platform you were running?
Platform was chrome, ran the same example you have provided and nothing changed. @Amir-P 

Observation: If editor was empty and the image was the first embedded then the cursor was blinking and not moving to new line some times!, if not empty and had few texts then the cursor working fine, but the log i have given was coming for all the cases!

**Comment by Amir-P** [comment]
I wasn't able to reproduce the issue but I've made a small change to add a new line after the inserted image in the example. @Chandu-bs
