### ISSUE TITLE
Prevent deletion of certain blocks via delete key + preventing caret appearing on that line (i.e. skipping that block). 

### ISSUE THREAD

**Issue by nialljawad96** [fleather-editor/fleather#228]
**Is your feature request related to a problem? Please describe.**
Is it possible to prevent the deletion of certain blocks via the backspace/delete key on the keyboard + also to prevent the caret/cursor from appearing on the same line on as a block? 

**Describe the solution you'd like**
A way to do the above. A bit like how Notion prevents you from deleting a "page" block with the backspace, and instead skips that block with the cursor.

**Describe alternatives you've considered**
I'm able to make custom blocks but I can't modify how the backspace/deletion/cursor interacts with them.

**Comment by Amir-P** [comment]
I think it is possible to achieve something like that with what we have now. You can create a custom heuristic which will check if deletion is affecting your block and prevent it by returning an empty delta. Let me know if you need more details or it's not what you want.

**Comment by nialljawad96** [comment]
@Amir-P I'm unsure how to do this. Would you be able to provide a super quick example? I imagine this would be a delete rule right?

**Comment by Amir-P** [comment]
Sorry for the late response @nialljawad96. Looks like it's harder than what I thought. @amantoux Do you know any way to achieve this behavior?

**Comment by amantoux** [comment]
Maybe this requires a dev, it needs further investigation

**Comment by nialljawad96** [comment]
I was able to do this by attaching a listener to the FleatherController object. I would then assess whether there was a certain block on the line the cursor was on, using DeltaIterator, and would turn a boolean flag true. Using a FocusNode above FleatherField, I'd then detect for the presence of the backspace key and the boolean flag being true. If it was, I'd prevent it from being propagated below to the FleatherField, and so prevent any deletion of the block.
