### ISSUE TITLE
onChange listener and getText functionality.

### ISSUE THREAD

**Issue by sunilsharma2** [fleather-editor/fleather#253]
**onChange listener needed to get the length of text entered so that in case maxlength we can easily calculate the length of character entered**

Needed to get the text entered so that on preview the details the tags functionality will be previewed properly.

Solution needed:
onChange listener that listen real time text character entered.
getText() function by which we can get the text entered along with the tags.

**Comment by Amir-P** [comment]
> **onChange listener needed to get the length of text entered so that in case maxlength we can easily calculate the length of character entered**
> 
> 
> 
> Needed to get the text entered so that on preview the details the tags functionality will be previewed properly.
> 
> 
> 
> Solution needed:
> 
> onChange listener that listen real time text character entered.
> 
> getText() function by which we can get the text entered along with the tags.
> 
> 

Hi, sorry your issue is a bit hard to understand for me. Do you want to get the characters count in the document after each update? What is a tag?

**Comment by sunilsharma2** [comment]
I want onChange listener as in text field. also when we bold the text  I want to get the <b> tag along the text but currently getting plainText.
Also please update the internal packages you are using as it's incompatible with lastest version.

**Comment by Amir-P** [comment]
> I want onChange listener as in text field.

Have you tried listening to controller?

```dart
controller.addListener(() {
  print(controller.document.toPlainText());
});
```

>also when we bold the text I want to get the tag along the text but currently getting plainText.

I'm sorry but I still can't understand what tag is. Can you provide an example document and what you want to find in the document?

> Also please update the internal packages you are using as it's incompatible with lastest version.

It should be fixed after publishing #257 .

**Comment by sunilsharma2** [comment]
By tags my mean to say if write some text with bold it should show as <b> hello</b> instead of plainText.
Also I noticed that if we put FleatherEditor inside SingleChildScrollview it's inner scroll lags.

**Comment by Amir-P** [comment]
> By tags my mean to say if write some text with bold it should show as < b > hello < / b>instead of plainText.

What you're asking for is the HTML representation of Parchment document. Fleather is using Parchment document with Quill Delta model and you can use `ParchmentHtmlCodec` from `parchment` package to convert it to HTML.
```dart
final document = ParchmentDocument();
final html = ParchmentHtmlCodec().encode(document);
```

> Also I noticed that if we put FleatherEditor inside SingleChildScrollview it's inner scroll lags.

For scrolling problem, please create a separated issue with reproducible example.

**Comment by sunilsharma2** [comment]
Where to put this code. Can you please help.
I have used this code as
controller.addListener(() {
  print(controller.document.toPlainText());
final document = ParchmentDocument();
final html = ParchmentHtmlCodec().encode(document);
}); but no getting empty data . Please help.

**Comment by sunilsharma2** [comment]
final document = controller.document;
final html = ParchmentHtmlCodec().encode(document);
Works but can you please help how to set initial text  in the Fleathercontroller as we did in textfield as
controller.text= "abcdefgsbsb";
