### ISSUE TITLE
parchment v1.14.0 not working

### ISSUE THREAD

**Issue by fgonzalez-tenco** [fleather-editor/fleather#255]
### Discussed in https://github.com/fleather-editor/fleather/discussions/254

<div type='discussions-op-text'>

<sup>Originally posted by **fgonzalez-tenco** January 29, 2024</sup>
Hello! 
I'm working with a flutter app and I'm having some issues while trying to build my application:

1. `flutter clean`
2. `flutter clean cache`
3. `flutter pub get`
4. `flutter build apk --no-tree-shake-icons`

The version used are:
- Fleather -> 1.11.0
- Flutter ->  3.16.9 (Channel stable)

Also, I tried with the following combination:
- Fleather -> 1.13.0
- Flutter ->  3.16.5 (Channel stable)

And the following errors were showed: 
![image](https://github.com/fleather-editor/fleather/assets/67757445/e4f7f113-a9d7-4e2d-adb7-ca133b7c591e)

Also, if I try to use the newest version of Fleatter (1.13.2 or 1.14.0+1) I got an error on the `flutter pub get` command: 
![image](https://github.com/fleather-editor/fleather/assets/67757445/45198d56-eed4-47af-ac9c-931d4ae1c892)

**Comment by fgonzalez-tenco** [comment]
I just found a way to make it build and it was:

In the pubspec.yaml refer to the specific fleather version:
` fleather: 1.13.0 `
And then, override the parchment dependency:
`dependency_overrides:
  parchment: 1.13.0`

**Comment by Amir-P** [comment]
Please use the latest version of ‘fleather‘ and ‘parchment‘ and instead add ‘intl: ^0.18.1‘ to your ‘dependency_overrides‘.

**Comment by fgonzalez-tenco** [comment]
Nope, that didn't worked:

![image](https://github.com/fleather-editor/fleather/assets/67757445/3de36060-f8e6-4c92-9f8c-047c28521807)

The other way that it worked was using:
`fleather: ^1.13.0`
`intl: ^0.18.1`

**Comment by Amir-P** [comment]
Please upgrade to the newest version. It should work now. @fgonzalez-tenco 

```yaml
fleather: ^1.14.1
```
