### ISSUE TITLE
Delete Error

### ISSUE THREAD

**Issue by sanghyun8039** [fleather-editor/fleather#259]
## Steps to Reproduce

1. ...Type Text
2. ...Select All
![스크린샷 2024-02-01 150158](https://github.com/fleather-editor/fleather/assets/3152174/0a5cd2ee-9ee7-4691-8742-bbee6515823f)

3. ...Click Delete Btn
![스크린샷 2024-02-01 150218](https://github.com/fleather-editor/fleather/assets/3152174/f14b2c5a-618f-4946-a0ed-c1e506912c2c)

## Environment
- OS [AOS]
- Flutter version [3.19.0-9.0.pre.173]
- Fleather version [1.14.1]

## Logs

```
```

**Comment by amantoux** [comment]
Can you please confirm the error does not occur with Flutter 3.16 @sanghyun8039 ?

**Comment by Jiseeeh** [comment]
I'm on flutter `3.19.1` and also getting this error when deleting text.
![image](https://github.com/fleather-editor/fleather/assets/80168125/329b461e-6851-4541-b7a0-d12371bb1127)
![image](https://github.com/fleather-editor/fleather/assets/80168125/7f677769-76c6-4d0a-92bd-09a9ddada2b9)

**Comment by amantoux** [comment]
We haven't yet tested the app on Flutter 3.19
We need to plan this

**Comment by Amir-P** [comment]
Hi @Jiseeeh, Could you please test if this is still happening with latest release (v1.14.3)?

**Comment by Jiseeeh** [comment]
Hello @Amir-P , sure! I'll test it later or tomorrow and I'll get back here asap.

One thing i notice was when i switched to quill editor because of this error, I also encountered it there. but running it on my physical device seems to have no problem, so im thinking if fleather will also work fine if i run the app in my phone not with the emulator.

**Comment by Jiseeeh** [comment]
Good day @Amir-P,

I tried it on the emulator and this was the error I got, this occurred when I was just deleting text **holding down the backspace.**
![image](https://github.com/fleather-editor/fleather/assets/80168125/0d65f3a9-9a33-4a9f-b064-aa271eb8c225)

And this was the error In my phone. This occurred when I was holding down the enter button.
![image](https://github.com/fleather-editor/fleather/assets/80168125/3c6904f2-c21f-4e71-99a7-1c3291db7f05)

**Comment by Amir-P** [comment]
Thanks for your investigation. I was able to reproduce the issue and I'm working on it. @Jiseeeh @sanghyun8039

**Comment by Amir-P** [comment]
It's possible to trigger this exception just by running this code on an Android emulator and pressing hardware keyboard backspace button. The issue is sending editing state with invalid composing range which itself is result of not storing composing range in controller.

```dart
import 'package:fleather/fleather.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const FleatherApp());
}

class FleatherApp extends StatelessWidget {
  const FleatherApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData.light(),
        darkTheme: ThemeData.dark(),
        title: 'Fleather - rich-text editor for Flutter',
        home: HomePage(),
      );
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final FocusNode _focusNode = FocusNode();
  final _controller = FleatherController(
      document: ParchmentDocument.fromJson([
    {'insert': 'Test test t\n'}
  ]));

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) =>
        _controller.updateSelection(TextSelection.collapsed(offset: 11)));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(elevation: 0, title: Text('Fleather Demo')),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _controller.replaceText(9, 2, '',
            selection: TextSelection.collapsed(offset: 9)),
        child: Icon(Icons.add_a_photo),
      ),
      body: Column(
        children: [
          FleatherToolbar.basic(controller: _controller),
          Divider(height: 1, thickness: 1, color: Colors.grey.shade200),
          Expanded(
            child: FleatherEditor(
              controller: _controller,
              focusNode: _focusNode,
              padding: EdgeInsets.only(
                left: 16,
                right: 16,
                bottom: MediaQuery.of(context).padding.bottom,
              ),
              maxContentWidth: 800,
            ),
          ),
        ],
      ),
    );
  }
}
```

Cc:  @amantoux

**Comment by Amir-P** [comment]
Could you please check if #304 fixes your issue? You can do so by using this in your `pubspec.yaml`:
```yaml
fleather:
  git:
    url: https://github.com/fleather-editor/fleather
    ref: fix/sending_invalid_composing_range_to_engine
    path: packages/fleather
```
@Jiseeeh @sanghyun8039
