### ISSUE TITLE
Clear Text Issue

### ISSUE THREAD

**Issue by irfanjutt67** [fleather-editor/fleather#265]
## Steps to Reproduce

1. ...
2. ... clear data function
3.  clearField() {
    if (editorController.document.length > 0) {
      editorController.document.delete(0, editorController.document.length);
    }
  }
  OR
    final docLength = editorController.document.length;
    editorController.document.delete(0, docLength);

4. ... click on delete button
      Failed assertion: line 206 pos 12: 'offset >= 0 && offset <= length': is not true.

## Environment
- OS [e.g. iOS]
- Flutter version [e.g. 3.10.0]
- Fleather version [e.g. 1.8.0]

## Logs

```
```

**Comment by Amir-P** [comment]
You shouldn't remove the last newline in document. Use this instead:

```dart
controller.replaceText(0, _controller.document.length - 1, '', selection: TextSelection.collapsed(offset: 0));
```

**Comment by irfanjutt67** [comment]
> You shouldn't remove the last newline in document. Use this instead:
> 
> ```dart
> controller.replaceText(0, _controller.document.length - 1, '', selection: TextSelection.collapsed(offset: 0));
> ```

thanks is working

**Comment by alesalv** [comment]
@Amir-P why wouldn't you add a controller.cleanText() method to the package?

**Comment by alesalv** [comment]
@Amir-P I would like to be able to clean any selection of the toolbar, the moment I clear the text via the controller ... how can I accomplish it, any idea?
I'm using FleatherToolbar.basic()

**Comment by alesalv** [comment]
@Amir-P thanks, opened two issues [here](https://github.com/fleather-editor/fleather/issues/382) and [here](https://github.com/fleather-editor/fleather/issues/383)
