### ISSUE TITLE
How to set html text initially in fleathereditor

### ISSUE THREAD

**Issue by sunilsharma2** [fleather-editor/fleather#266]
I want to set text in the the fleatherEditor initially like we do in textfield as textfield controller.text= 'abcd';
What I am trying to do is saving the description text which is written using fleatherEditor with ParchmentHtmlCodec().encode(document) to the server and on the next screen want to get the same description initially from the api and put that description text in the fleather editor with ParchmentHtmlCodec().decode(document).
Please help.

**Comment by amantoux** [comment]
We'd advise to store the document with delta on the server. This will guarantee that the data stored on the server can be used to instantiate the document on the next screen @sunilsharma2

**Comment by sunilsharma2** [comment]
@amantoux how to set the data initially in the fleather editor. Can you please give an example.

**Comment by amantoux** [comment]
As describred in the README.md
There are serveral ways to create a document (from JSON or Delta).
Then create the controller with that document
```dart
document = ParchmentDocument.fromJson(json);
//or 
document = ParchmentDocument.fromDelta(delta);
controller = FleatherController(document);
```

**Comment by sunilsharma2** [comment]
I have copy and paste buttons in toolbar,how can I paste the data in fleatherEditor.
Also as you suggest to save the delta in server so how can this can be displayed in flutter_html widget.

**Comment by amantoux** [comment]
@sunilsharma2 
You can use `controller.replaceText(int index, int length, Object data, {TextSelection? selection})` to paste the data.
To display the document in a HTML container, you can indeed use `ParchmentHtmlCodec().encode(document)`. `document` can be retrieved from controller likewise `controller.document`

**Comment by sunilsharma2** [comment]
@amantoux It works but on paste the cursor doesn't move next to the paste text.

**Comment by amantoux** [comment]
Indeed you need to set the selection accordingly

**Comment by sunilsharma2** [comment]
@amantoux can you provide me an code example as I have tried but not working.

**Comment by amantoux** [comment]
@sunilsharma2 
When setting select, consider the position of the cursor in the new document (that has been augmented by data.text.length)

Re HTML encorder, you must have an additional trailing `\n`, `hello\n` should be encoded to `hello`
