### ISSUE TITLE
Can we set character limit in fleatherEditor?

### ISSUE THREAD

**Issue by sunilsharma2** [fleather-editor/fleather#270]
In fleatherEditor/fleatherfield can we set the character limit as we do maxlength in textformfield.

**Comment by amantoux** [comment]
@sunilsharma2 There is not such setting.
But you can easily control the number of character at controller level
```dart
if (controller.document.length >= threshold) return;
controller.replaceText(....);
```

**Comment by sunilsharma2** [comment]
if (controller.document.length >= threshold) return;
controller.replaceText(....);
@amantoux Where to add this line of code?

**Comment by amantoux** [comment]
when listening to the controller
```dart
_controller.addListener(() {
  if (_controller.document.length > threshold) {
    final overflow = _controller.document.length - threshold; 
    _controller.replaceText(threshold - 1, overflow, "");
  }
});
```

**Comment by sunilsharma2** [comment]
_controller.addListener(() {
  if (_controller.document.length > threshold) {
    final overflow = _controller.document.length - threshold; 
    _controller.replaceText(threshold - 1, overflow, "");
  }
});

@amantoux It works but now new issue arises, as user trying to type after 2000 limit he is not able to type but if user set cursor inbetween already typed text and start typing he can type and existing text start replacing from end.
Kindly look into the issue.

**Comment by amantoux** [comment]
@sunilsharma2 simply adapt the above code to handle this case
