### ISSUE TITLE
Cursor not moving while pasting

### ISSUE THREAD

**Issue by jacquetc** [fleather-editor/fleather#271]
Hello, 

Nice text editor ! I hope to use it in my writing software if I ditch Qt. I'm a Rust and C++/Qt developer, so it's not hell for me to help you bit, so here is my first little contribution. I already solved this bug in my fork and want to trace it here to give you a pull request. I know that it's better to ask before changing anything, but it's so small... I hope this benign modification is good for you.

I found this behavioral problem while pasting :

### Encountered behavior
1. Run the flutter example
2. Select a sentence
3. Copy using the shortcut
4. Paste immediately without deselecting
5. Paste again immediately without moving the cursor
6. Bug: Nothing change visually (yes, I know it actually pasted on the selection)

### Expected Behavior 

1. Run the flutter example
2. Select a sentence
3. Copy using the shortcut
4. Paste immediately without deselecting
5. Expected: unselect and pet the cursor at the end of the paste
6. Paste again immediately without moving the cursor
7. Expected: the pasting is repeated at the current position of the cursor

## Environment
- OS Linux (KDE Neon on Wayland)
- Flutter version 3.16.19
- Fleather version 1.14.1

## Logs

```
```

**Comment by amantoux** [comment]
@jacquetc Thank you for spotting this.
