### ISSUE TITLE
Is there a way to check if text has been copied/pasted/cut?

### ISSUE THREAD

**Issue by nialljawad96** [fleather-editor/fleather#289]
Is there a way to check if text has been copied/pasted/cut, via a listener or something similar?

**Comment by Amir-P** [comment]
Sorry for the delay. I've been busy. You can provide your own clipboard manager which handles reading and writing clipboard data. When user wants to copy or cut the data, `setData` will be called and when user wants to paste the data, `getData` will be called. Let me know if it solves your problem.
```dart
clipboardManager:
    FleatherCustomClipboardManager(getData: () async {
  print('user wants to paste');
  return FleatherClipboardData(
    plainText: await Clipboard.getData(Clipboard.kTextPlain)
        .then((v) => v?.text),
  );
}, setData: (data)  {
  print('user wants to copy or cut');
  return Clipboard.setData(
      ClipboardData(text: data.plainText ?? ''));
}),
```

**Comment by nialljawad96** [comment]
This works brilliantly. Thanks!
