### ISSUE TITLE
Mobile cursor bug with keyboard suggestions

### ISSUE THREAD

**Issue by badayumut** [fleather-editor/fleather#296]
## Steps to Reproduce

Open editor. Type something and click keyboard suggestion. Press enter for new line and cursors blinks in two lines. Reproducible also in quill editor package. 

## Environment
- OS Android
- Flutter version 3.19
- Fleather version 1.14.2

## Logs

```
```

**Comment by badayumut** [comment]
https://github.com/fleather-editor/fleather/assets/143794438/7e948bb9-ded1-4c46-8059-36592823a4a3

**Comment by Amir-P** [comment]
Thank you for bringing this to our attention. Can you please confirm that the same problem doesn't happen with Flutter's own TextField widget in multiline state? @badayumut

**Comment by badayumut** [comment]
Sure. 


https://github.com/fleather-editor/fleather/assets/143794438/f6a088bd-98d5-475d-af99-9801a2d89da3
`class TextFieldDemo extends StatelessWidget {
  const TextFieldDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Container(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: TextField(
              minLines: 5,
              maxLines: 5,
            ),
          ),
        ),
      ),
    );
  }
}`

**Comment by maelchiotti** [comment]
I do have the exact same issue.

**Comment by Amir-P** [comment]
Thank you for investigating it. I'm able to reproduce the issue and working on to fix it. @badayumut @maelchiotti

**Comment by Amir-P** [comment]
Sorry if it took so long. I think I have a fix for this issue. Could you please check if #305 resolves this? @badayumut @maelchiotti 
```yaml
fleather:
  git:
    url: https://github.com/fleather-editor/fleather
    ref: fix/wrong_cursor_state_on_text_line_node_update
    path: packages/fleather
```

**Comment by Amir-P** [comment]
> @Amir-P Fixed for me on Android, yes!

Glad to hear that! Let's wait for @amantoux to review the PR.
