### ISSUE TITLE
Wrong cursor position When Mixing RTL and LTR Text

### ISSUE THREAD

**Issue by bcmehdi8** [fleather-editor/fleather#302]
I notice an issue of wrong cursor positioning when writing arabic (RTL) with any other LTR language, the cursor issue is related only to LTR text, the cursor should be in the beginning of the LTR word when typing LTR text rather than the end of the word

This issue appear while Direction is set to RTL and TextAlignment set to Right

Here's the issue on Latest fleather demo

https://github.com/fleather-editor/fleather/assets/44551268/b40b58e7-5443-4815-b9c3-6c708d63f712

Here's an example of how the cursor should behave around LTR words

https://github.com/fleather-editor/fleather/assets/44551268/c55119c1-3d7d-48eb-b7d3-59820b6b73b3

## Environment
- Android 14
- Flutter version 3.19.4
- Fleather version 1.14.2

Thanks for this Amazing package!

**Comment by Amir-P** [comment]
Thanks for creating the issues! I have to say I'm not text editing expert, but there seems to be no standard for it and it's rather a design choice in different platforms and rich text editing softwares. Here are some examples:

Flutter's `TextField` on iOS:
<img width="352" alt="Screenshot 2024-04-11 at 16 47 42" src="https://github.com/fleather-editor/fleather/assets/8766492/b8e82efd-a935-4add-8f02-03f148209b93">

Flutter's `TextField` on Android:
<img width="357" alt="Screenshot 2024-04-11 at 16 49 17" src="https://github.com/fleather-editor/fleather/assets/8766492/675a9fc1-1447-4ce3-a2e3-e87387a60fce">

Flutter's `TextField` on Web (macOS):
<img width="209" alt="Screenshot 2024-04-11 at 16 57 12" src="https://github.com/fleather-editor/fleather/assets/8766492/629f4b3d-3d21-4f13-842b-72aef291bd9d">

Microsoft Word on macOS:
<img width="189" alt="Screenshot 2024-04-11 at 16 35 38" src="https://github.com/fleather-editor/fleather/assets/8766492/4ae20942-3003-4fa5-b471-3ddf6dc9e972">

Google Docs (Web):
<img width="131" alt="Screenshot 2024-04-11 at 16 38 49" src="https://github.com/fleather-editor/fleather/assets/8766492/16f84080-31ab-4008-af76-9bab2c5d42db">

Apple Notes on macOS:
<img width="140" alt="Screenshot 2024-04-11 at 16 39 47" src="https://github.com/fleather-editor/fleather/assets/8766492/7d448d77-9542-4938-af87-b0f251cdf303">

It seems like our editor behaves the same as Flutter's `TextField` but that doesn't necessarily mean it's the correct behavior and it has to be this way. Both way of painting cursor have advantages and disadvantages. When cursor is painted at the end of line (leftmost) when user types an RTL character it would be inserted where cursor was but if types LTR it will be inserted in the end of LTR text part and not where the cursor was.

Do you have any thoughts or proposal for this? @bcmehdi8

**Comment by Amir-P** [comment]
A few more references to look at:

- https://marijnhaverbeke.nl/blog/cursor-in-bidi-text.html
- https://medium.com/phrase-engineering/handling-bi-directional-text-web-editor-d4a543d1a3b1
- http://www.unicode.org/reports/tr9

**Comment by Amir-P** [comment]
Closing as there were no activities.
