### ISSUE TITLE
Toolbar shows previous paragraph formatting after inserting new paragraph

### ISSUE THREAD

**Issue by Alspb** [fleather-editor/fleather#307]
Although all inline formatting is reset when inserting a new paragraph, the previous paragraph formatting is displayed on the toolbar until the user starts entering text.
For example, if some bold text is entered, and then Enter is pressed, the new line is marked as bold while in fact it doesn't preserve bold formatting. See the screenshot below:
![Fleather toolbar formatting bug](https://github.com/fleather-editor/fleather/assets/73047043/782ac641-ba37-4455-b1d1-08e2d9477a2c)

## Environment
- OS [any]
- Flutter version [3.19.3]
- Fleather version [master]

**Comment by Amir-P** [comment]
Thanks for reporting the issue. It's reproducible. Looks like we are always moving selection one position backward to collect styles when selection is collapsed and it causes problems when selection is on the beginning of a new line. @Alspb
