### ISSUE TITLE
Incorrect cursor movement after pasting copied text.

### ISSUE THREAD

**Issue by Alspb** [fleather-editor/fleather#311]
## Steps to Reproduce

1. Run the example.
2. Double press on "beginning" word, copy it.
3. Place the cursor right after "beginning" word.
4. Paste copied text.

As a result, pasting works fine, but the cursor moves into the last paragraph for some reason.

## Environment
- OS [any]
- Flutter version [3.19.3]
- Fleather version [master]

**Comment by Amir-P** [comment]
Thanks for bringing this to our attention. It's reproducible.
