### ISSUE TITLE
Heading 6 TextBlockTheme is not applied.

### ISSUE THREAD

**Issue by Kontrano** [fleather-editor/fleather#312]
I noticed a bug in the FleatherThemeData where the TextBlockTheme for Heading 6 is not applied to the text. 

To reproduce: Try to set it with the color red: 

Heading 6 is set to be red.
![image](https://github.com/fleather-editor/fleather/assets/80490564/d62c57ea-f56a-4f67-bcf6-f91fd742d63d)
In the selection, it is not red. Neither is it in the editor when set.
![image](https://github.com/fleather-editor/fleather/assets/80490564/36e5fc66-8f19-4502-922c-e2cbed86f545)

**Comment by Amir-P** [comment]
Thanks for reporting the issue. It's reproducible.
