### ISSUE TITLE
Cursor is covered by keyboard

### ISSUE THREAD

**Issue by no-chili** [fleather-editor/fleather#315]
When getting focus, if it is covered by the keyboard, it will not automatically scroll to the cursor position. I need to enter manually.

https://github.com/fleather-editor/fleather/assets/79079747/91dc5f80-f5a9-4c4d-8c98-2b8ccbf0cd93

**Comment by no-chili** [comment]
I've tried using a scrollController to manually control the scroll, but there seems to be no way to get the cursor's position in the text

**Comment by Amir-P** [comment]
Could you please verify that you're using the latest version (v1.14.3)? @no-chili

**Comment by no-chili** [comment]
https://github.com/fleather-editor/fleather/assets/79079747/16a24ce2-4ac3-480c-99e3-6299e1be8b4b

I am using a custom picture component, which will vibrate

**Comment by Amir-P** [comment]
Closing as the original issue is already resolved.
