### ISSUE TITLE
Using custom components will vibrate

### ISSUE THREAD

**Issue by no-chili** [fleather-editor/fleather#316]
There may be some bad things about this
I am using a custom picture component, which will vibrate

https://github.com/fleather-editor/fleather/assets/79079747/0967ea03-c4bc-41f8-aa58-34cc2a243118

_Originally posted by @no-chili in https://github.com/fleather-editor/fleather/issues/315#issuecomment-2041433478_

**Comment by no-chili** [comment]
> Hi @no-chili, Could you please test if #320 fixes your problem?嗨，您能测试一下是否 #320 解决了您的问题吗？
> 
> ```yaml
>   fleather:
>     git:
>       url: https://github.com/fleather-editor/fleather
>       ref: fix/scroll_to_reveal_cursor_bigger_than_viewport
>       path: packages/fleather
> ```

It is now working fine on both the simulator and the actual device. Thank you for your fix.

**Comment by no-chili** [comment]
I'm sorry, I accidentally clicked on close.

**Comment by Amir-P** [comment]
No problem. Thanks for testing it. We will add the tests and merge it then. @no-chili
