### ISSUE TITLE
Invalid document delta

### ISSUE THREAD

**Issue by mahdinba97** [fleather-editor/fleather#326]
## Steps to Reproduce

I want to implement copy/paste functionality from/to a rich text.
1. create a page with FleaterEditor widget in it.
2. add custom clipboard manager.
3. export Parchment Document from data.delta (in `setData` method). by calling  `ParchmentDocument.fromDelta()`
4. should work as expected and result in a Parchment Document, but results in exception.

code: 
``` dart
FleatherEditor(
  clipboardManager: FleatherCustomClipboardManager(
    getData: () async {
      final data = await Clipboard.getData(Clipboard.kTextPlain);

      final codec = _codec.decoder.convert(data?.text ?? '');
      return FleatherClipboardData(
        delta: codec.toDelta(),
        plainText: codec.toPlainText(),
      );
    },
    setData: (data) async {

      try {
        final document = ParchmentDocument.fromDelta(data.delta!);
        Clipboard.setData(ClipboardData(text: ParchmentMarkdownCodec().encode(document)));
      } catch (e) {
        log(e.toString(), name: 'error in parchment');
      }
    },
  ),
  controller: _controller,
)
```

## Environment
- Android 13
- Flutter version 3.19.4
- Fleather version 1.14.4

## Logs

```
 'package:parchment/src/document.dart': Failed assertion: line 311 pos 12: '(doc.last.data as String).endsWith('\n')': Invalid document delta. Document delta must always end with a line-break.
```

**Comment by mahdinba97** [comment]
We can fix this by adding a `\n` at the end of the delta. But anyways can't we have the pasted text with no trailing enter characters?

**Comment by Amir-P** [comment]
This requirement is enforced by the `ParchmentDocument` and I think it should stay the same. @mahdinba97 
For convenience we can provide a util function (named `normalizeDeltaForParchment` or something like that) which takes care of adding the last new line or other `ParchmentDocument` requirements to your delta and make it ready to be parsed by `ParchmentDocument`.

CC: @amantoux
