### ISSUE TITLE
Unable to use the Enter key

### ISSUE THREAD

**Issue by no-chili** [fleather-editor/fleather#327]
After inserting an image, line breaks malfunction. It works fine in iOS and Android emulators, but this issue only occurs on Android physical devices.

**Comment by no-chili** [comment]
Thank you for your response. I asked some users, and it seems to be working fine on their phones. Perhaps it's just a conflict on my device.

**Comment by Amir-P** [comment]
No problem! I'm gonna close this issue but feel free to reopen if you encounter the issue again. @no-chili
