### ISSUE TITLE
Add hintText for editor

### ISSUE THREAD

**Issue by komakur** [fleather-editor/fleather#328]
Currently it's impossible to set hint text for the editor

**Comment by Amir-P** [comment]
Have you considered using 'FleatherField'? @komakur

**Comment by komakur** [comment]
> Have you considered using ’FleatherField’? @komakur 

if it gives same functionalities as FleatherEditor I might consider using that.
But I didn't find clear docs about FleatherField

**Comment by komakur** [comment]
oh, I see now
Thanks a lot)

**Comment by komakur** [comment]
@Amir-P  the problem now, that the toolbar in FleatherField is always at the bottom, thus is visible when its focused. I think that should be customisable

**Comment by Amir-P** [comment]
What do you mean by toolbar? Providing a screenshot or video may help. @komakur

**Comment by no-chili** [comment]
Thank you for your response. I asked some users, and it seems to be working fine on their phones. Perhaps it's just a conflict on my device.

**Comment by komakur** [comment]
By toolbar I mean toolbar param in FleatherField. You can simply go to [FleatherField impl](https://github.com/fleather-editor/fleather/blob/4f97476ad3a44ff6e7b0324b2b6a105d4f6fccdf/packages/fleather/lib/src/widgets/field.dart#L262C4-L275C6) and check the implementation

**Comment by Amir-P** [comment]
The `toolbar` params is useful when you want to show toolbar below field but inside the input decorator. If you want your toolbar to be on top, don't use `toolbar` param of `FleatherField` and instead add toolbar widget by yourself. For example:

```dart
Column(
  children: [
    FleatherToolbar.basic(controller: controller),
    FleatherField(controller: controller),
  ],
)
```

**Comment by amantoux** [comment]
Closing this issue for now as it has been stale for a while.
Feel free to re-open
