### ISSUE TITLE
Support Flutter 3.3

### ISSUE THREAD

**Issue by Amir-P** [fleather-editor/fleather#34]
Flutter 3.3 again has changes in text editing API and now provides granular text changes (deltas).

**Comment by bkraszewski** [comment]
@Amir-P is my error in recent Flutter related to delta operations?

`The following TypeErrorImpl was thrown while dispatching notifications for FleatherController:
Expected a value of type 'String', but got one of type 'List<Operation>'

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49                          throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 99:3                            castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 452:10                      cast
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 705:17                                    as
packages/gdziepolekcjach/feature/editor/create_edit_activity/create_edit_activity_screen.dart 201:46  <fn>
packages/flutter/src/foundation/change_notifier.dart 351:24                                           notifyListeners
packages/fleather/src/widgets/controller.dart 111:5                                                   replaceText
packages/fleather/src/widgets/editor_input_client_mixin.dart 35:10                                    [_remoteValueChanged]
packages/fleather/src/widgets/editor_input_client_mixin.dart 157:7                                    updateEditingValue
packages/flutter/src/services/text_input.dart 1801:9                                                  _handleTextInputInvocation
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                    runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                    _async
packages/flutter/src/services/text_input.dart 1716:45                                                 [_handleTextInputInvocation]
packages/flutter/src/services/text_input.dart 1701:20                                                 _loudlyHandleTextInputInvocation
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                    runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                    _async
packages/flutter/src/services/text_input.dart 1699:51        `

**Comment by Amir-P** [comment]
What did you do that caused this issue? Can you provide a reproducible example? @bkraszewski

**Comment by bkraszewski** [comment]
@Amir-P I'm on 3.3.5, Flutter web. When I click on the editor, I can not see caret, when I start typing it works as expected but can see the error in the log. Will post extracted code.
Using Chrome 106.0.5249

**Comment by bkraszewski** [comment]
@Amir-P Today I created a new project to reproduce this issue and everything worked fine - I'll try adding other dependencies I'm using to see if it breaks

**Comment by Amir-P** [comment]
> @Amir-P Today I created a new project to reproduce this issue and everything worked fine - I'll try adding other dependencies I'm using to see if it breaks

Thanks, it would help a lot if you provide an example. Also, which version of Fleather are you using?

**Comment by dsyrstad** [comment]
@bkraszewski @Amir-P I'm successfully using fleather 1.3.0 on web and linux. It works great. Thank you for this package!
