### ISSUE TITLE
Unexpected Double New Line Issue When Pressing Enter

### ISSUE THREAD

**Issue by Zuhaib50** [fleather-editor/fleather#362]
I'm running the example code and facing an issue. When I tap 'Enter' to go to the next line, it adds two new lines instead of one. However, when I reach a new line while typing, it behaves correctly and moves to the next line as expected. Can you please check this issue?

https://github.com/fleather-editor/fleather/assets/59314201/f09f0cc0-2720-46d5-8569-4c35aec087cf

**Comment by simonbengtsson** [comment]
The default style in fleather is to add some spacing for each paragraph. You can remove that and make it similar to apple notes etc by setting spacing to zero for the text theme

```dart
TextBlockTheme(spacing: VerticalSpacing.zero());
```

**Comment by Amir-P** [comment]
As @simonbengtsson pointed out, there is no extra new line added when you press enter but a new paragraph is created which has extra spacing that you can customize. I'm closing this but feel free to reopen if your issue persists or if you have any further questions. @Zuhaib50
