### ISSUE TITLE
Improve the colors of inline code and code blocks

### ISSUE THREAD

**Issue by maelchiotti** [fleather-editor/fleather#363]
## Steps to Reproduce

1. Add some inline code or a code block

I find the colors of inline code and code blocks make them hard to use:
- In light mode (pure white background), the code block especially is so light that I can barely distinguish it from the background. I prefer the background color of the inline code.
- In dark mode, and even more in black mode, the background of the inline code and the code block should really be a dark gray. The inline code also has some really bad contrast that make it hard to read.

![Screenshot_2024-06-03-09-43-19-289_com.maelchiotti.localmaterialnotes.jpg](https://github.com/fleather-editor/fleather/assets/44336112/5dbd3c83-0281-455a-9f25-fe091a537633)

![Screenshot_2024-06-03-09-43-38-448_com.maelchiotti.localmaterialnotes.jpg](https://github.com/fleather-editor/fleather/assets/44336112/de8c1e42-54d2-4f61-a79b-67e8fe4bc939)

![Screenshot_2024-06-03-09-43-44-608_com.maelchiotti.localmaterialnotes.jpg](https://github.com/fleather-editor/fleather/assets/44336112/44b23820-9255-4437-8ec1-7f8a627d475b)

## Environment
- OS: Android
- Flutter version: 3.22
- Fleather version: 1.14.5+1

**Comment by Amir-P** [comment]
Our default theme does not care much about the brightness and the base app theme. We need to improve it but for now it's better to customize it the way you want.

**Comment by maelchiotti** [comment]
In the meantime, if it can be useful to anyone: here is how I customized the theme in my material 3 app. Inline code and code blocks look great in light, dark and black theme, with or without dynamic colors. I also made the text colors the same.

```dart
@override
Widget build(BuildContext context) {
  final theme = Theme.of(context);
  final fleatherThemeFallback = FleatherThemeData.fallback(context);

  return FleatherTheme(
    data: fleatherThemeFallback.copyWith(
      inlineCode: InlineCodeThemeData(
        backgroundColor: theme.colorScheme.surfaceContainerHigh, // Changed
        radius: fleatherThemeFallback.inlineCode.radius,
        style: fleatherThemeFallback.inlineCode.style.copyWith(
          color: theme.colorScheme.primary, // Changed
        ),
        heading1: fleatherThemeFallback.inlineCode.heading1,
        heading2: fleatherThemeFallback.inlineCode.heading2,
        heading3: fleatherThemeFallback.inlineCode.heading3,
      ),
      code: TextBlockTheme(
        decoration: fleatherThemeFallback.code.decoration!.copyWith(
          color: theme.colorScheme.surfaceContainerHigh, // Changed
        ),
        style: fleatherThemeFallback.code.style.copyWith(
          color: theme.colorScheme.primary, // Changed
        ),
        spacing: fleatherThemeFallback.code.spacing,
      ),
    ),
    child: FleatherField(
      controller: FleatherController(),
    ),
  );
}
```

**Comment by Amir-P** [comment]
Thanks! I haven't checked it yet but do you want to create a PR? @maelchiotti

**Comment by maelchiotti** [comment]
Yeah why not! That would be my first ever! I'll fork the repo and check that my modifications do work properly

**Comment by maelchiotti** [comment]
@Amir-P done in #365! Let me know over there if anything needs to be changed.
