### ISSUE TITLE
Add controller's clear() method

### ISSUE THREAD

**Issue by alesalv** [fleather-editor/fleather#382]
**Is your feature request related to a problem? Please describe.**
I use FleatherEditor to send messages like in a normal chat app, so once the message is sent I would like to have an handy method to clear the whole edited message, instead of using [this workaround](https://github.com/fleather-editor/fleather/issues/265#issuecomment-1925615845)

**Describe the solution you'd like**
Instead I would like to be able to do:

`controller.clear();
`

similar to [TextEditingController.clear()](https://api.flutter.dev/flutter/widgets/TextEditingController/clear.html)

**Comment by Amir-P** [comment]
Thanks for opening the issue. Sorry for the late response I'm having really busy life recently but I will do my best to implement it. In the meantime feel free to contribute if you want.

**Comment by alesalv** [comment]
Thanks for taking care of this, I will 👀 for now 😄

**Comment by Amir-P** [comment]
Hey @alesalv. Could you please test #393 and see if it works as expected?
