### ISSUE TITLE
FontSize option

### ISSUE THREAD

**Issue by mahdimostafa** [fleather-editor/fleather#392]
**Is your feature request related to a problem? Please describe.**
Hi, I like this package, but I have one issue: I am unable to select the option for font size, and I realized there isn't one.

**Describe the solution you'd like**
I'm not sure how simple this is, but I would like to ask if you can add a font size selection.

**Describe alternatives you've considered**
I have tried creating my own selection, but I have encountered some issues that prevent me from freely selecting the sizes.

**Additional context**
N/A

**Comment by kfdykme** [comment]
@mahdimostafa  https://github.com/fleather-editor/fleather/blob/master/packages/fleather/lib/src/widgets/text_line.dart#L254  maybe this is what you need？I change fontSize by change FleatherTheme's text style

**Comment by manudicri** [comment]
Hi, is it possible to reopen this?
Currently in the toolbar there's no option to change the fontSize of a piece of string. I don't want to change the fontSize of all.
I think this is pretty limiting.
