### ISSUE TITLE
Touch Event is not correct while scroll to no-top

### ISSUE THREAD

**Issue by kfdykme** [fleather-editor/fleather#397]
https://github.com/user-attachments/assets/058e4064-505a-4ea1-9a4d-282828326177

## Steps to Reproduce

1. run a simple demo of fleather with  scrollable is true (andorid/web also can reproduce)
2. build a scrollable editor (for me, copy all text , and paste it twice)
3. make chekcbox for all lines
4. scroll to anywhere not top
5. try to click checkbox ,

## Environment
- OS  
web
- Flutter version 
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter
Framework • revision 761747bfc5 (9 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
- Fleather version [e.g. 1.8.0]
1.17.0, I reproduce this from version 1.15 to 1.17, and also reproduce at the latest commit e7c7a9ac64b32c148f4e5e168a0f262fc55dbf14
## Reason

I think the reason is there is a EditorTextSelectionGestureDetectorBuilder outside and is Scrollable with ViewPort inside, so the Touch Event can not hit correctly.

Fortunately, this can be resolved easily by setting the scrollable property to false within the relevant code segment.

``` dart
diff --git a/packages/fleather/lib/src/widgets/editor.dart b/packages/fleather/lib/src/widgets/editor.dart
index 4337930..7551830 100644
--- a/packages/fleather/lib/src/widgets/editor.dart
+++ b/packages/fleather/lib/src/widgets/editor.dart
@@ -1719,7 +1719,7 @@ class RawEditorState extends EditorState
       child = CompositedTransformTarget(
         link: _toolbarLayerLink,
         child: Semantics(
-          child: _Editor(
+          child: SingleChildScrollView(child: _Editor(
             key: _editorKey,
             offset: ViewportOffset.zero(),
             document: widget.controller.document,
@@ -1733,7 +1733,7 @@ class RawEditorState extends EditorState
             padding: widget.padding,
             maxContentWidth: widget.maxContentWidth,
             children: _buildChildren(context),
-          ),
+          ),),
         ),
       );
     } 
```

This does not address the root cause of the problem. Since I'm not familiar with this code, I can only post an issue for further assistance.

**Comment by amantoux** [comment]
Thank you for reporting this @kfdykme!
After some investigation, it seems related to this https://github.com/flutter/flutter/issues/72996
I'll work on a fix

**Comment by amantoux** [comment]
@kfdykme  can you please give it a try with this?
```yaml
  fleather:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: fix/hit_test_fails_when_scrolled
      path: packages/fleather
```
