### ISSUE TITLE
hide editor featured

### ISSUE THREAD

**Issue by irfanjutt67** [fleather-editor/fleather#416]
when i add width than my editor featured hide and there is not scroll show 

  fleather: ^1.16.0

![O](https://github.com/user-attachments/assets/59602182-4ec7-41b4-9456-864ff3e77dfc)
 Column(
                                                  crossAxisAlignment:
                                                      CrossAxisAlignment.start,
                                                  children: [
                                                    normalText(text: 'Note'),
                                                    Container(
                                                      width: double.maxfinite,
                                                      height: 50,
                                                      decoration:
                                                          const BoxDecoration(
                                                              gradient:
                                                                  editorColor),
                                                      child:
                                                          FleatherToolbar.basic(
                                                              controller:
                                                                  controller
                                                                      .note),
                                                    ),
                                                    Container(
                                                      decoration: BoxDecoration(
                                                          border: Border.all(
                                                              color: Colors.grey
                                                                  .withOpacity(
                                                                      0.5))),
                                                      child: FleatherField(
                                                              minHeight: 150,
                                                              maxHeight: 250,
                                                              decoration: const InputDecoration(
                                                                  border:
                                                                      InputBorder
                                                                          .none),
                                                              controller:
                                                                  controller
                                                                      .note)
                                                          .paddingSymmetric(
                                                              horizontal: 8),
                                                    ),
                                                  ]),

**Comment by amantoux** [comment]
@irfanjutt67 are you referring to the fact the toolbar is clipped and that it cannot be scrolled?

**Comment by amantoux** [comment]
This is related to responsiveness of the toolbar (issue raised https://github.com/fleather-editor/fleather/issues/274) so it might not be obvious but you should be able to scroll horizontally the toolbar

Please close the issue if the horizontal scrolling works as expected
