### ISSUE TITLE
Headings in the toolbar don't make use of the styles defined by FleatherTheme

### ISSUE THREAD

**Issue by kane-knowby** [fleather-editor/fleather#423]
## Steps to Reproduce

1. Wrap your FleatherToolbar with a FleatherTheme
2. Observe heading styles are not reflected when choosing a heading from toolbar
3. Specifically heading 5 is always underlined which is main problem for us

## Environment
OS: iOS/Web/Android
Flutter version: 3.24
Fleather version: 1.18.0

**Comment by amantoux** [comment]
Closing a stale for some time
Feel free to re-open
