### ISSUE TITLE
Bug Ordered List on view

### ISSUE THREAD

**Issue by rymesaint** [fleather-editor/fleather#437]
Using ordered list or unordered list error

## Steps to Reproduce

1. Create a list of ordered list or unordered list
2. display using ParchmentDocument.fromJson()
3. got Error type null is not a subtype of type Object

## Environment
- OS Windows
- Flutter version 3.24.3
- Fleather version 1.19.0

## Logs

![Screenshot 2024-11-08 142749](https://github.com/user-attachments/assets/c416b42c-ffc6-42ba-906a-476206e75abf)

```json
[{"insert": "Selamat Siang,\nPeraturan"}, {"insert": "Rumah Mode", "attributes": {"b": true}}, {"insert": "Mohon untuk mengikuti aturan yang sudah diberikan sebagai berikut :\nBerpakaian Rapi"}, {"insert": null, "attributes": {"block": "ol"}}, {"insert": "Stylish"}, {"insert": null, "attributes": {"block": "ol"}}, {"insert": "Berpengalaman"}, {"insert": null, "attributes": {"block": "ol"}}, {"insert": null}]
```

**Comment by amantoux** [comment]
@rymesaint try replacing `null` with `\n` your delta's
