### ISSUE TITLE
Support for markdown decoding

### ISSUE THREAD

**Issue by Pierre2tm** [fleather-editor/fleather#46]
Hi,

We need a wysiwyg markdown editor in our app and we are considering using Fleather package.
For this we need to initialize the editor with pre-existing markdown data and also extract markdown from the editor data.
We only need basic markdown for now.

I've spotted the `ParchmentMarkdownCodec.encode` function that let us convert deltas to markdown formatted text, but the `ParchmentMarkdownCodec.decode` isn't implemented yet and if I'm right it's needed to load markdown formatted text inside the editor.

Is there any way to do this actually?

**Comment by amantoux** [comment]
Indeed it is not yet implemented. It should be in the near future

Feel free to propose an implementation.
