### ISSUE TITLE
Open HTML document

### ISSUE THREAD

**Issue by DerKnerd** [fleather-editor/fleather#53]
Hey,

I am currently writing a mobile app for a CMS I develop. In the web app I currently use tinyMCE, is it possible to load the HTML into fleather or convert it to open?

Greetings
DerKnerd

**Comment by Amir-P** [comment]
Hey @DerKnerd ,

It's possible to have a codec for Delta and HTML but it's not implemented in Fleather yet. Also there are attributes in HTML that Parchment and Fleather don't support yet and you have to handle it. I've started implementing this codec a few months ago but I couldn't finish it. You can implement it yourself and contribute your solution. 

Here are a few useful links to get started:
https://github.com/memspace/zefyr/issues/51#issuecomment-444757035
https://github.com/memspace/zefyr/pull/59
https://github.com/memspace/zefyr/pull/178
https://github.com/memspace/zefyr/issues/460
https://pub.dev/packages/notustohtml
https://github.com/nozer/quill-delta-to-html

**Comment by DerKnerd** [comment]
The package looks great, thanks a lot.
