### ISSUE TITLE
Rich clipboard

### ISSUE THREAD

**Issue by amantoux** [fleather-editor/fleather#56]
When copy some text (including embeds), pasting it back in the same Fleather widget should preserve format & embeds.

Three use-cases are foreseen:
1. #### Copy/paste from/to a Fleather editor to/from an external app. 
    We assume that the OS clipboard holds HTML or plain text. The content should be converted to Delta thanks to HTML codec. Copying some text from Fleather to the clipboard will convert ParchmentDocument Deltas to HTML prior to setting it to the clipboard.
2. #### Copy from a Fleather editor to another Fleather editor. 
    Copying from one Fleather editor to another Fleather editor should be using Delta format
3. #### Copy from a position to another position within a same Fleather editor
     Same as 2.

**Comment by Amir-P** [comment]
How can we know user is pasting from `FleatherEditor`?

**Comment by amantoux** [comment]
> How can we know user is pasting from a `FleatherEditor`? @amantoux

My guess would be that any delta format would be picked in priority
But I haven't thought this through yet, I'm simple state the ideal setup

**Comment by cgestes** [comment]
maybe using something like https://github.com/superlistapp/super_native_extensions/blob/ab9629d67a4d0b0e64c4b5239935b9b6eb5178a1/super_clipboard/lib/src/standard_formats.dart#L204

**Comment by simonbengtsson** [comment]
I've been using the editor now for the past few months in my note editor app and this is likely my main feature request. The main two rich text features I tend to use are bullet points and links both of which would be extremely nice to be able to copy and paste to new notes.

**Comment by amantoux** [comment]
> I've been using the editor now for the past few months in my note editor app and this is likely my main feature request. The main two rich text features I tend to use are bullet points and links. Both of which would be extremely nice to be able to copy and paste to new notes.

@simonbengtsson thank you for upvoting this. It is next in our roadmap!
