### ISSUE TITLE
[Desktop] When focus is on editor, cursor should be in text selection mode

### ISSUE THREAD

**Issue by amantoux** [fleather-editor/fleather#65]
Currently it is in using basic arrow
This seems limited to macOS (TBC)
https://github.com/flutter/flutter/issues/111425

**Comment by amantoux** [comment]
Didn't have a chance to test with Flutter 3.3
Will do shortly

**Comment by Amir-P** [comment]
I tested it out on macOS with Flutter 3.7 and it looks to be working correctly. @amantoux @MohammedSalehelShazly 
```
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (8 weeks ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
```

**Comment by amantoux** [comment]
Thanks @Amir-P  for testing
Closing the issuer in that case
