### ISSUE TITLE
Is there any way to customise theme for toolbar such as colors, background, shape?

### ISSUE THREAD

**Issue by amangautam1** [fleather-editor/fleather#79]

**Comment by amantoux** [comment]
The toolbar is provided for convenience, it relies on Fleather's public controller.
You can easily implement your own by copying and customizing it.

**Comment by amangautam1** [comment]
Got it. But could you provide any example for toggle any formatting button using controller?

**Comment by amantoux** [comment]
You can look at `ToggleStyleButton` in `editor_toolbar.dart`
Essentially, you need to call `controller.formatSelection`

**Comment by cgestes** [comment]
Check here: https://github.com/fleather-editor/fleather/blob/master/packages/parchment/lib/src/heuristics/insert_rules.dart#L121

**Comment by amantoux** [comment]
Can we close this issue?
