### ISSUE TITLE
is there any way to prevent formatting reset while  pressing enter/new line ?

### ISSUE THREAD

**Issue by amangautam1** [fleather-editor/fleather#81]
## Steps to Reproduce
1) Select any formatting from toolbar
2) Press enter from keyboard
3) formatting will reset to default

It might be intended behavior but can we prevent it in any case?

**Comment by amantoux** [comment]
Indeed, this is the intended format.
Can you please explain when such a behavior is required?

**Comment by amangautam1** [comment]
We want to use it for poetic kind of context. The content is centered most of case with few words per line, on pressing new line the new line again start from left alignment and with default formatting, it should be copy formatting from last line.

Can we add a config to enable/disable it from controller? Or  behavior of resetting formatting on double new line(\n\n)?

**Comment by cgestes** [comment]
Check here: https://github.com/fleather-editor/fleather/blob/master/packages/parchment/lib/src/heuristics/insert_rules.dart#L121

you can probably disable it from here: https://github.com/fleather-editor/fleather/blob/master/packages/parchment/lib/src/heuristics.dart

this is not very customisable at the moment, but it would make sense to have options to configure the editor where it makes sense I guess.

**Comment by amantoux** [comment]
stale
