### ISSUE TITLE
Emoji handling

### ISSUE THREAD

**Issue by zaynetro** [fleather-editor/fleather#84]
This issue is more like a question. 

Quill delta uses String.length when calculating the length of inserted string. This works with normal text but with a single emoji it returns the length=2. This works alright when you handle Parchment doc. My problem is that I convert Parchment doc to my own format where I count characters. 

Do you have any suggestions how to bridge these two worlds together?

My only thought so far was to replace emojis with inline embeds.

Sample test:

```dart
    test('insert after emoji', () {
      final doc = ParchmentDocument();
      doc.insert(0, '😀');
      doc.insert(1, '!');
      final expectedDoc = Delta()
        ..insert('😀1\n');
      expect(doc.toDelta(), expectedDoc);
    });
```

Output:

```
00:17 +162 -1: parchment/test/document_test.dart: ParchmentDocument insert after emoji [E]
  Expected: Delta:<insert⟨ 😀1⏎ ⟩>
    Actual: Delta:<insert⟨ �!�⏎ ⟩>

  package:test_api               expect
  test/document_test.dart 403:7  main.<fn>.<fn>
```

P.S I see that Fleather imports `characters` package but I don't see where that package is used. Is it used anywhere?

**Comment by amantoux** [comment]
It might require adapting Delta iterator in `quill_delta` and counting `Character`s using [characters](https://pub.dev/documentation/characters/latest/characters/Characters-class.html)
Sound like a heavy load of work to achieve this.

inline embeds sounds a good idea for the moment 😃

re-PS: Couldn't find where `characters` is used neither; we should probably remove it
