### ISSUE TITLE
Indentation issues when applied to checklist

### ISSUE THREAD

**Issue by amantoux** [fleather-editor/fleather#86]
## Steps to Reproduce

1. Create a checklist with 3 items
2. Apply indentation to the second one
3. Apply indentation twice to third one
     **Indentation is heterogenous**
4. de-indent twice third item
     **Item isn't in the right place**

**Comment by Amir-P** [comment]
@amantoux Can you record a video of the problem you've explained? Because after following steps to reproduce, beside the text moving away from it's checkbox, I can't see any other problem.

https://user-images.githubusercontent.com/8766492/217546221-d9e8479d-1d40-4d4e-ae91-5e3642b01d98.mp4

**Comment by Amir-P** [comment]
> Notice how distance between checkbox & text get bigger as you add indentation?

Got it. That's what I noticed myself but I thought you're talking about other problem. @amantoux

**Comment by amantoux** [comment]
> Got it. That's what I noticed myself but I thought you're talking about other problem. @amantoux

Yes there is another problem too, I'll see if I can still reproduce it
I noticed it on desktop though

**Comment by amantoux** [comment]
> > Got it. That's what I noticed myself but I thought you're talking about other problem. @amantoux
> 
> Yes there is another problem too, I'll see if I can still reproduce it I noticed it on desktop though

It only occurs when performing a hot reload, so we can ignore it
