### ISSUE TITLE
There are any way to read docs which wrote with zefyr ?

### ISSUE THREAD

**Issue by MohammedSalehelShazly** [fleather-editor/fleather#93]

**Comment by Amir-P** [comment]
Can you share a document you've created with `zefyr` which isn't compatible with `fleather`? BTW, I saw your question on SO and asked you the same there. @MohammedSalehelShazly

**Comment by MohammedSalehelShazly** [comment]
Most of the keys were changed like "bold", "italic", "underline", ...
changed with "b", "i", "u", ...
also video, image, collapsible, divider

### fleather wrote video and image like that:
```
{
        "insert": {
            "source": "https://...",
            "_type": "image",
            "_inline": false
        }
    },
    {
        "insert": {
            "source": "https://www.youtube.com/...",
            "_type": "video",
            "_inline": false
        }
    }
```

### but zfyre wrote it like that:
```
{
    "insert": "​",
    "attributes": {
      "embed": {
        "type": "image",
        "source": "https://..."
      }
    }
  },
  {
    "insert": "​",
    "attributes": {
      "embed": {
        "type": "video",
        "source": "https://www.youtube.com/..."
      }
    }
  }
```

I tried to write code to convert zefyr document to fleather, I will publish it soon.
@Amir-P

**Comment by Amir-P** [comment]
> @Amir-P  How to delete a node!
> 
> I tried to use `controller.document.delete(node.offset, node.length)` to delete a node from the document
> 
> but this error occurs to me and when I write something, the document does not update in time.
> 
> ```
> 
> Bad state: Compose produced inconsistent results. This is likely due to a bug in the library. Tried to compose change retain⟨ 4 ⟩
> 
> insert⟨ s⏎ ⟩ from ChangeSource.local.
> 
> ```

Can you provide a reproducible code? It's hard to tell without. @MohammedSalehelShazly

**Comment by amantoux** [comment]
Stale

**Comment by MohammedSalehelShazly** [comment]
Thanks, it solved
but I have one more question, How can I handle insert formated
I have text documents like:
```
{
    'insert': 'Formatted TEXT',
    'attributes': ['u': true, 'b': true, .. ]
}
```

> Note: I tried to handle copy/past for text (with its attributes).
Thank You @Amir-P  .

**Comment by amantoux** [comment]
You mean

```
{
  'insert': 'Formatted TEXT',
  'attributes': {
    'u': true, 
    'b': true, 
    .. 
  }
}
```

**Comment by Amir-P** [comment]
@MohammedSalehelShazly  You can do this:

```dart
final text = 'Inserted text at index 10';
controller.replaceText(14, 0, text);
controller.formatText(14, text.length, ParchmentAttribute.bold);
```
